// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPeX_e3HgYltWRh6DqykR3djVbLVWdWs',
    appId: '1:185138983559:web:230356c366409c7d7c3e22',
    messagingSenderId: '185138983559',
    projectId: 'twclone-12ce6',
    authDomain: 'twclone-12ce6.firebaseapp.com',
    storageBucket: 'twclone-12ce6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwvKlPyLsnFFEfvySeu1Tk1OJNIJolIU',
    appId: '1:185138983559:android:c8cee44547a43d6e7c3e22',
    messagingSenderId: '185138983559',
    projectId: 'twclone-12ce6',
    storageBucket: 'twclone-12ce6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Y8Xc4gJZ2gfmh-uXxeuI53w_y3flkb8',
    appId: '1:185138983559:ios:7625bf6f530314447c3e22',
    messagingSenderId: '185138983559',
    projectId: 'twclone-12ce6',
    storageBucket: 'twclone-12ce6.appspot.com',
    iosBundleId: 'com.example.social2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Y8Xc4gJZ2gfmh-uXxeuI53w_y3flkb8',
    appId: '1:185138983559:ios:96deab030afcb49c7c3e22',
    messagingSenderId: '185138983559',
    projectId: 'twclone-12ce6',
    storageBucket: 'twclone-12ce6.appspot.com',
    iosBundleId: 'com.example.social2.RunnerTests',
  );
}
